apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellers-v1
  namespace: sellers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sellers
      version: v1
  template:
    metadata:
      labels:
        app: sellers
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - image: suhyung007/sellers:tomcat-15
          name: sellers
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sellers-persistent-storage
              mountPath: /var/lib
      volumes:
        - name: sellers-persistent-storage
          persistentVolumeClaim:
            claimName: sellers-pv-claim 
